//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitSocial.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "The name field is required!")]
        [DisplayName("Name :")]
        public string Name { get; set; }

        [Required(ErrorMessage = "The surname field is required!")]
        [DisplayName("Surname :")]
        public string Surname { get; set; }

        [Required(ErrorMessage = "The email field is required!")]
        [DataType(DataType.EmailAddress)]
        [DisplayName("Email Address :")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [RegularExpression(@"^(?=.{6,}$)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W).*$",
                            ErrorMessage = "Password must contain: atleast one number, atleast one special character, and both uppercase and lowwercase.")]
        [Display(Name = "Password:")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
